version: 2

jobs:

  build:
    docker:
      - image: openjdk:8-jdk
      - image: mongo
      - image: redis

    working_directory: /opt/user-service

    steps:
      - run:
          name: Install system dependencies
          command: |
            apt-get update
            apt-get install apt-transport-https ca-certificates software-properties-common -y

      - run:
          name: Install SBT
          command: |
            echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
            apt-get update
            apt-get install sbt -y

      - checkout

      - restore_cache:
          key: app-dependencies

      - run:
          name: Compile app
          command: sbt compile

      - run:
          name: Run tests
          command: sbt test

      - save_cache:
          key: app-dependencies
          paths:
            - /root/.sbt
            - /root/.ivy2